/// This file has messages for describing authentication

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: users/accounts/accounts_v1.proto

package accounts

import (
	applications "github.com/badhouseplants/envspotting-go-proto/models/apps/applications"
	common "github.com/badhouseplants/envspotting-go-proto/models/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Represents credentials (username and password)
type AccountCreds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // username: unix-like
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Password
}

func (x *AccountCreds) Reset() {
	*x = AccountCreds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreds) ProtoMessage() {}

func (x *AccountCreds) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreds.ProtoReflect.Descriptor instead.
func (*AccountCreds) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCreds) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountCreds) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

//*
// Represents Account ID only
type AccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AccountId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

//*
// Represents username only
type AccountName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // username
}

func (x *AccountName) Reset() {
	*x = AccountName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountName) ProtoMessage() {}

func (x *AccountName) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountName.ProtoReflect.Descriptor instead.
func (*AccountName) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{2}
}

func (x *AccountName) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

//*
// Represents the Account without sensitive data
type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // UUID
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // username: unix-like
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{3}
}

func (x *AccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type FullAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // UUID
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // username: unix-like
	GitlabToken string `protobuf:"bytes,3,opt,name=gitlab_token,json=gitlabToken,proto3" json:"gitlab_token,omitempty"`
}

func (x *FullAccountInfo) Reset() {
	*x = FullAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullAccountInfo) ProtoMessage() {}

func (x *FullAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullAccountInfo.ProtoReflect.Descriptor instead.
func (*FullAccountInfo) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{4}
}

func (x *FullAccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FullAccountInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FullAccountInfo) GetGitlabToken() string {
	if x != nil {
		return x.GitlabToken
	}
	return ""
}

type AccountInfoWithSensitive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // UUID
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // username: unix-like
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // Password
	GitlabToken string `protobuf:"bytes,4,opt,name=gitlab_token,json=gitlabToken,proto3" json:"gitlab_token,omitempty"`
}

func (x *AccountInfoWithSensitive) Reset() {
	*x = AccountInfoWithSensitive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoWithSensitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoWithSensitive) ProtoMessage() {}

func (x *AccountInfoWithSensitive) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoWithSensitive.ProtoReflect.Descriptor instead.
func (*AccountInfoWithSensitive) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{5}
}

func (x *AccountInfoWithSensitive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfoWithSensitive) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountInfoWithSensitive) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountInfoWithSensitive) GetGitlabToken() string {
	if x != nil {
		return x.GitlabToken
	}
	return ""
}

type PasswordUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	OldPassword string `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
}

func (x *PasswordUpdate) Reset() {
	*x = PasswordUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdate) ProtoMessage() {}

func (x *PasswordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdate.ProtoReflect.Descriptor instead.
func (*PasswordUpdate) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PasswordUpdate) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordUpdate) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *PasswordUpdate) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type AccountsListOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName *AccountName   `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Paging      *common.Paging `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *AccountsListOptions) Reset() {
	*x = AccountsListOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountsListOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsListOptions) ProtoMessage() {}

func (x *AccountsListOptions) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsListOptions.ProtoReflect.Descriptor instead.
func (*AccountsListOptions) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{7}
}

func (x *AccountsListOptions) GetAccountName() *AccountName {
	if x != nil {
		return x.AccountName
	}
	return nil
}

func (x *AccountsListOptions) GetPaging() *common.Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type GitlabToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GitlabToken string `protobuf:"bytes,1,opt,name=gitlab_token,json=gitlabToken,proto3" json:"gitlab_token,omitempty"` // Gitlab token
}

func (x *GitlabToken) Reset() {
	*x = GitlabToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_users_accounts_accounts_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitlabToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitlabToken) ProtoMessage() {}

func (x *GitlabToken) ProtoReflect() protoreflect.Message {
	mi := &file_users_accounts_accounts_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitlabToken.ProtoReflect.Descriptor instead.
func (*GitlabToken) Descriptor() ([]byte, []int) {
	return file_users_accounts_accounts_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GitlabToken) GetGitlabToken() string {
	if x != nil {
		return x.GitlabToken
	}
	return ""
}

var File_users_accounts_accounts_v1_proto protoreflect.FileDescriptor

var file_users_accounts_accounts_v1_proto_rawDesc = []byte{
	0x0a, 0x20, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x27, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x1b, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x29, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x0f, 0x46, 0x75, 0x6c, 0x6c, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x18, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x74, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x30, 0x0a, 0x0b, 0x47, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x97, 0x03, 0x0a,
	0x08, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x64, 0x73, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x46, 0x75, 0x6c,
	0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x2d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x35,
	0x0a, 0x07, 0x53, 0x65, 0x6c, 0x66, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x33, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x54, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0b, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x49, 0x64, 0x1a, 0x14,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32, 0x4d, 0x0a, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x12, 0x43, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x10, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a,
	0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x00, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x6c, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d,
	0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_users_accounts_accounts_v1_proto_rawDescOnce sync.Once
	file_users_accounts_accounts_v1_proto_rawDescData = file_users_accounts_accounts_v1_proto_rawDesc
)

func file_users_accounts_accounts_v1_proto_rawDescGZIP() []byte {
	file_users_accounts_accounts_v1_proto_rawDescOnce.Do(func() {
		file_users_accounts_accounts_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_users_accounts_accounts_v1_proto_rawDescData)
	})
	return file_users_accounts_accounts_v1_proto_rawDescData
}

var file_users_accounts_accounts_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_users_accounts_accounts_v1_proto_goTypes = []interface{}{
	(*AccountCreds)(nil),             // 0: users.AccountCreds
	(*AccountId)(nil),                // 1: users.AccountId
	(*AccountName)(nil),              // 2: users.AccountName
	(*AccountInfo)(nil),              // 3: users.AccountInfo
	(*FullAccountInfo)(nil),          // 4: users.FullAccountInfo
	(*AccountInfoWithSensitive)(nil), // 5: users.AccountInfoWithSensitive
	(*PasswordUpdate)(nil),           // 6: users.PasswordUpdate
	(*AccountsListOptions)(nil),      // 7: users.AccountsListOptions
	(*GitlabToken)(nil),              // 8: users.GitlabToken
	(*common.Paging)(nil),            // 9: common.Paging
	(*applications.AppId)(nil),       // 10: apps.AppId
	(*common.EmptyMessage)(nil),      // 11: common.EmptyMessage
}
var file_users_accounts_accounts_v1_proto_depIdxs = []int32{
	2,  // 0: users.AccountsListOptions.account_name:type_name -> users.AccountName
	9,  // 1: users.AccountsListOptions.paging:type_name -> common.Paging
	0,  // 2: users.Accounts.Create:input_type -> users.AccountCreds
	4,  // 3: users.Accounts.UpdateUser:input_type -> users.FullAccountInfo
	6,  // 4: users.Accounts.UpdatePassword:input_type -> users.PasswordUpdate
	1,  // 5: users.Accounts.Get:input_type -> users.AccountId
	1,  // 6: users.Accounts.SelfGet:input_type -> users.AccountId
	7,  // 7: users.Accounts.List:input_type -> users.AccountsListOptions
	10, // 8: users.Accounts.AddAppToUser:input_type -> apps.AppId
	1,  // 9: users.Tokens.GetGitlabTokenByAccountID:input_type -> users.AccountId
	3,  // 10: users.Accounts.Create:output_type -> users.AccountInfo
	4,  // 11: users.Accounts.UpdateUser:output_type -> users.FullAccountInfo
	11, // 12: users.Accounts.UpdatePassword:output_type -> common.EmptyMessage
	3,  // 13: users.Accounts.Get:output_type -> users.AccountInfo
	4,  // 14: users.Accounts.SelfGet:output_type -> users.FullAccountInfo
	3,  // 15: users.Accounts.List:output_type -> users.AccountInfo
	11, // 16: users.Accounts.AddAppToUser:output_type -> common.EmptyMessage
	8,  // 17: users.Tokens.GetGitlabTokenByAccountID:output_type -> users.GitlabToken
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_users_accounts_accounts_v1_proto_init() }
func file_users_accounts_accounts_v1_proto_init() {
	if File_users_accounts_accounts_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_users_accounts_accounts_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoWithSensitive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountsListOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_users_accounts_accounts_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitlabToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_users_accounts_accounts_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_users_accounts_accounts_v1_proto_goTypes,
		DependencyIndexes: file_users_accounts_accounts_v1_proto_depIdxs,
		MessageInfos:      file_users_accounts_accounts_v1_proto_msgTypes,
	}.Build()
	File_users_accounts_accounts_v1_proto = out.File
	file_users_accounts_accounts_v1_proto_rawDesc = nil
	file_users_accounts_accounts_v1_proto_goTypes = nil
	file_users_accounts_accounts_v1_proto_depIdxs = nil
}
