/// This file has messages for describing contours

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: apps/contours/contours_v1.proto

package contours

import (
	common "github.com/allanger/gitlab-environment-aggregator/models/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Represents an contour UUID only
type ContourId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Contour ID: UUID
}

func (x *ContourId) Reset() {
	*x = ContourId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContourId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContourId) ProtoMessage() {}

func (x *ContourId) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContourId.ProtoReflect.Descriptor instead.
func (*ContourId) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ContourId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContoursListOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Applcation ID: UUID
}

func (x *ContoursListOption) Reset() {
	*x = ContoursListOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContoursListOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContoursListOption) ProtoMessage() {}

func (x *ContoursListOption) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContoursListOption.ProtoReflect.Descriptor instead.
func (*ContoursListOption) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ContoursListOption) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ContourIdAndName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                    // UUID
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                // Contour name: Unique string
	AppId string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Applcation ID: UUID
}

func (x *ContourIdAndName) Reset() {
	*x = ContourIdAndName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContourIdAndName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContourIdAndName) ProtoMessage() {}

func (x *ContourIdAndName) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContourIdAndName.ProtoReflect.Descriptor instead.
func (*ContourIdAndName) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{2}
}

func (x *ContourIdAndName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContourIdAndName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContourIdAndName) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ContourInfoWithoutServices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ContourInfoWithoutServices) Reset() {
	*x = ContourInfoWithoutServices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContourInfoWithoutServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContourInfoWithoutServices) ProtoMessage() {}

func (x *ContourInfoWithoutServices) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContourInfoWithoutServices.ProtoReflect.Descriptor instead.
func (*ContourInfoWithoutServices) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ContourInfoWithoutServices) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContourInfoWithoutServices) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContourInfoWithoutServices) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ContourNameAndDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AppId       string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Applcation ID: UUID
}

func (x *ContourNameAndDescription) Reset() {
	*x = ContourNameAndDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContourNameAndDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContourNameAndDescription) ProtoMessage() {}

func (x *ContourNameAndDescription) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContourNameAndDescription.ProtoReflect.Descriptor instead.
func (*ContourNameAndDescription) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ContourNameAndDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContourNameAndDescription) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContourNameAndDescription) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

//*
// Represents a full contour
type ContourInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // UUID
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Contour name: Unique string
	Description string         `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Services    []*ServiceInfo `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`        // Array of maps <projectID:environmentID>
	AppId       string         `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Applcation ID: UUID
}

func (x *ContourInfo) Reset() {
	*x = ContourInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContourInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContourInfo) ProtoMessage() {}

func (x *ContourInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContourInfo.ProtoReflect.Descriptor instead.
func (*ContourInfo) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ContourInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContourInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContourInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ContourInfo) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ContourInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

//*
// Represents a service without ID
type ServiceWithoutId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project     int64 `protobuf:"varint,1,opt,name=project,proto3" json:"project,omitempty"`         // Project ID from Gitlab
	Environment int64 `protobuf:"varint,2,opt,name=environment,proto3" json:"environment,omitempty"` //  Environment ID from Gitlab
}

func (x *ServiceWithoutId) Reset() {
	*x = ServiceWithoutId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceWithoutId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceWithoutId) ProtoMessage() {}

func (x *ServiceWithoutId) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceWithoutId.ProtoReflect.Descriptor instead.
func (*ServiceWithoutId) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceWithoutId) GetProject() int64 {
	if x != nil {
		return x.Project
	}
	return 0
}

func (x *ServiceWithoutId) GetEnvironment() int64 {
	if x != nil {
		return x.Environment
	}
	return 0
}

//*
// Represents a service
type ServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project     int64  `protobuf:"varint,2,opt,name=project,proto3" json:"project,omitempty"`         // Project ID from Gitlab
	Environment int64  `protobuf:"varint,3,opt,name=environment,proto3" json:"environment,omitempty"` //  Environment ID from Gitlab
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetProject() int64 {
	if x != nil {
		return x.Project
	}
	return 0
}

func (x *ServiceInfo) GetEnvironment() int64 {
	if x != nil {
		return x.Environment
	}
	return 0
}

type ServiceIdAndContourId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContourId string `protobuf:"bytes,1,opt,name=contour_id,json=contourId,proto3" json:"contour_id,omitempty"`
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
}

func (x *ServiceIdAndContourId) Reset() {
	*x = ServiceIdAndContourId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceIdAndContourId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdAndContourId) ProtoMessage() {}

func (x *ServiceIdAndContourId) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdAndContourId.ProtoReflect.Descriptor instead.
func (*ServiceIdAndContourId) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceIdAndContourId) GetContourId() string {
	if x != nil {
		return x.ContourId
	}
	return ""
}

func (x *ServiceIdAndContourId) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

//*
// Represents an array of services
type RepeatedServiceWithoutId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContourId string              `protobuf:"bytes,1,opt,name=contour_id,json=contourId,proto3" json:"contour_id,omitempty"`
	Services  []*ServiceWithoutId `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *RepeatedServiceWithoutId) Reset() {
	*x = RepeatedServiceWithoutId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedServiceWithoutId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedServiceWithoutId) ProtoMessage() {}

func (x *RepeatedServiceWithoutId) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedServiceWithoutId.ProtoReflect.Descriptor instead.
func (*RepeatedServiceWithoutId) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{9}
}

func (x *RepeatedServiceWithoutId) GetContourId() string {
	if x != nil {
		return x.ContourId
	}
	return ""
}

func (x *RepeatedServiceWithoutId) GetServices() []*ServiceWithoutId {
	if x != nil {
		return x.Services
	}
	return nil
}

//*
// Represents an array of services
type RepeatedServiceWithId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContourId string         `protobuf:"bytes,1,opt,name=contour_id,json=contourId,proto3" json:"contour_id,omitempty"`
	Services  []*ServiceInfo `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *RepeatedServiceWithId) Reset() {
	*x = RepeatedServiceWithId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_contours_contours_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedServiceWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedServiceWithId) ProtoMessage() {}

func (x *RepeatedServiceWithId) ProtoReflect() protoreflect.Message {
	mi := &file_apps_contours_contours_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedServiceWithId.ProtoReflect.Descriptor instead.
func (*RepeatedServiceWithId) Descriptor() ([]byte, []int) {
	return file_apps_contours_contours_v1_proto_rawDescGZIP(), []int{10}
}

func (x *RepeatedServiceWithId) GetContourId() string {
	if x != nil {
		return x.ContourId
	}
	return ""
}

func (x *RepeatedServiceWithId) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_apps_contours_contours_v1_proto protoreflect.FileDescriptor

var file_apps_contours_contours_v1_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x61, 0x70, 0x70, 0x73, 0x1a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1b, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x12,
	0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74,
	0x6f, 0x75, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x68, 0x0a, 0x19,
	0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x41, 0x6e, 0x64, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x6f,
	0x75, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x59, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x18, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x15, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x74, 0x68, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x70, 0x70, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x32, 0xd6, 0x03, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x41, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e,
	0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x1a, 0x11,
	0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x57, 0x69, 0x74, 0x68, 0x6f,
	0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x14,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x6f, 0x75, 0x74, 0x49, 0x64, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b,
	0x2e, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x41,
	0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x1a, 0x14, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6c, 0x6c, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x67,
	0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_contours_contours_v1_proto_rawDescOnce sync.Once
	file_apps_contours_contours_v1_proto_rawDescData = file_apps_contours_contours_v1_proto_rawDesc
)

func file_apps_contours_contours_v1_proto_rawDescGZIP() []byte {
	file_apps_contours_contours_v1_proto_rawDescOnce.Do(func() {
		file_apps_contours_contours_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_contours_contours_v1_proto_rawDescData)
	})
	return file_apps_contours_contours_v1_proto_rawDescData
}

var file_apps_contours_contours_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apps_contours_contours_v1_proto_goTypes = []interface{}{
	(*ContourId)(nil),                  // 0: apps.ContourId
	(*ContoursListOption)(nil),         // 1: apps.ContoursListOption
	(*ContourIdAndName)(nil),           // 2: apps.ContourIdAndName
	(*ContourInfoWithoutServices)(nil), // 3: apps.ContourInfoWithoutServices
	(*ContourNameAndDescription)(nil),  // 4: apps.ContourNameAndDescription
	(*ContourInfo)(nil),                // 5: apps.ContourInfo
	(*ServiceWithoutId)(nil),           // 6: apps.ServiceWithoutId
	(*ServiceInfo)(nil),                // 7: apps.ServiceInfo
	(*ServiceIdAndContourId)(nil),      // 8: apps.ServiceIdAndContourId
	(*RepeatedServiceWithoutId)(nil),   // 9: apps.RepeatedServiceWithoutId
	(*RepeatedServiceWithId)(nil),      // 10: apps.RepeatedServiceWithId
	(*common.EmptyMessage)(nil),        // 11: common.EmptyMessage
}
var file_apps_contours_contours_v1_proto_depIdxs = []int32{
	7,  // 0: apps.ContourInfo.services:type_name -> apps.ServiceInfo
	6,  // 1: apps.RepeatedServiceWithoutId.services:type_name -> apps.ServiceWithoutId
	7,  // 2: apps.RepeatedServiceWithId.services:type_name -> apps.ServiceInfo
	4,  // 3: apps.Contours.Create:input_type -> apps.ContourNameAndDescription
	0,  // 4: apps.Contours.Get:input_type -> apps.ContourId
	1,  // 5: apps.Contours.List:input_type -> apps.ContoursListOption
	3,  // 6: apps.Contours.Update:input_type -> apps.ContourInfoWithoutServices
	2,  // 7: apps.Contours.Delete:input_type -> apps.ContourIdAndName
	9,  // 8: apps.Contours.AddServices:input_type -> apps.RepeatedServiceWithoutId
	8,  // 9: apps.Contours.RemoveService:input_type -> apps.ServiceIdAndContourId
	3,  // 10: apps.Contours.Create:output_type -> apps.ContourInfoWithoutServices
	5,  // 11: apps.Contours.Get:output_type -> apps.ContourInfo
	5,  // 12: apps.Contours.List:output_type -> apps.ContourInfo
	3,  // 13: apps.Contours.Update:output_type -> apps.ContourInfoWithoutServices
	11, // 14: apps.Contours.Delete:output_type -> common.EmptyMessage
	11, // 15: apps.Contours.AddServices:output_type -> common.EmptyMessage
	11, // 16: apps.Contours.RemoveService:output_type -> common.EmptyMessage
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apps_contours_contours_v1_proto_init() }
func file_apps_contours_contours_v1_proto_init() {
	if File_apps_contours_contours_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_contours_contours_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContourId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContoursListOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContourIdAndName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContourInfoWithoutServices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContourNameAndDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContourInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceWithoutId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceIdAndContourId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedServiceWithoutId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_contours_contours_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedServiceWithId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_contours_contours_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_contours_contours_v1_proto_goTypes,
		DependencyIndexes: file_apps_contours_contours_v1_proto_depIdxs,
		MessageInfos:      file_apps_contours_contours_v1_proto_msgTypes,
	}.Build()
	File_apps_contours_contours_v1_proto = out.File
	file_apps_contours_contours_v1_proto_rawDesc = nil
	file_apps_contours_contours_v1_proto_goTypes = nil
	file_apps_contours_contours_v1_proto_depIdxs = nil
}
